controller_list:
  - name: fake_steering_wheels_controller
    type: $(arg fake_execution_type)
    joints:
      - fl_steering_wheel
      - fr_steering_wheel
      - rl_steering_wheel
      - rr_steering_wheel
  - name: fake_drive_wheels_controller
    type: $(arg fake_execution_type)
    joints:
      - fl_wheel
      - fr_wheel
      - rl_wheel
      - rr_wheel
initial:  # Define initial robot poses per group
  - group: steering_wheels
    pose: steering_start